# The name of the project
service: cloud-resume-challenge
frameworkVersion: '3'

custom:
  siteName: lpastor-website-bucket
  customDomain:
    domainName: luispastor.dev
    certificateName: 'luispastor.dev'
    createRoute53Record: true
  customCertificate:
    certificateName: 'luispastor.dev'
    hostedZoneName: 'luispastor.dev.' # don't forget the dot on the end - is required by Route53
  hostedZoneId: Z2FDTNDATAQYW2 # For CloudFront distributions, the value is always Z2FDTNDATAQYW2

# Configuration for AWS
provider:
  name: aws
  endpointType: REGIONAL
  region: ${opt:reginon, 'us-east-1'}
  # This enables us to use the default stage definition, but override it from the command line
  stage: ${opt:stage, 'dev'}
  runtime: python3.9
  iam:
    role:
      name: crc-${sls:stage}-role
      statements:       
        - Effect: Allow
          Action: 
            - 'dynamodb:UpdateItem'
          Resource: 
            - "Fn::GetAtt": [myDynamoDBTable, Arn]
  environment:
    ENV_MYTABLE: counterTable
     
functions:
  # Lambda function with API Gateway trigger
  get-visitors:
    handler: lambda_function/handler.lambda_handler
    events:
      - http:
          path: /counter
          method: get
          cors: true
          integration: lambda

resources:
  - ${file(resources/resources.yml)}
  - ${file(resources/outputs.yml)}
          
# Plugins for additional Serverless functionality
plugins:
  - serverless-certificate-creator
